PRAGMA foreign_keys = ON;

-- USERS TABLE
CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT UNIQUE,
    User_name TEXT NOT NULL UNIQUE,
    User_password TEXT,
    loggedIn INTEGER NOT NULL DEFAULT 0,
    Auto_Match INTEGER NOT NULL DEFAULT 0,
    isOnline INTEGER NOT NULL DEFAULT 0,
    avatar TEXT DEFAULT 'https://www.gravatar.com/avatar/',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- FRIEND REQUEST TABLE
CREATE TABLE IF NOT EXISTS FriendRequest (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    senderId INTEGER NOT NULL,
    receiverId INTEGER NOT NULL,
    Request_status TEXT NOT NULL DEFAULT 'PENDING' CHECK(Request_status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (senderId, receiverId),
    FOREIGN KEY (senderId) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (receiverId) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- TOURNAMENT TABLE
CREATE TABLE IF NOT EXISTS Tournament (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Label TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    count_player INTEGER NOT NULL DEFAULT 0,
    result TEXT NOT NULL DEFAULT 'PENDING' CHECK(result IN ('PENDING','WIN','LOSE')),
    Winner_Id INTEGER,
    Count INTEGER,
    FOREIGN KEY (Winner_Id) REFERENCES Users(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- PARTICIPATE TOURNAMENT TABLE
CREATE TABLE IF NOT EXISTS Participate_Tournament (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    P_Id INTEGER NOT NULL,
    T_Id INTEGER NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (P_Id, T_Id),
    FOREIGN KEY (P_Id) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (T_Id) REFERENCES Tournament(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- MATCH TABLE
CREATE TABLE IF NOT EXISTS MatchTable (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    P1_Id INTEGER NOT NULL,
    P2_Id INTEGER NOT NULL,
    score_player1 INTEGER NOT NULL DEFAULT 0,
    score_player2 INTEGER NOT NULL DEFAULT 0,
    mode INTEGER NOT NULL DEFAULT 2,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    result TEXT NOT NULL DEFAULT 'PENDING' CHECK(result IN ('PENDING','WIN','LOSE')),
    Winner_Id INTEGER,
    tournamentId INTEGER,
    FOREIGN KEY (P1_Id) REFERENCES Users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (P2_Id) REFERENCES Users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (Winner_Id) REFERENCES Users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (tournamentId) REFERENCES Tournament(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- MESSAGES TABLE
CREATE TABLE IF NOT EXISTS Messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Message_Text TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Sender INTEGER NOT NULL,
    Receiver INTEGER NOT NULL,
    FOREIGN KEY (Sender) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Receiver) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_friendrequest_sender ON FriendRequest(senderId);
CREATE INDEX IF NOT EXISTS idx_friendrequest_receiver ON FriendRequest(receiverId);
CREATE INDEX IF NOT EXISTS idx_messages_sender_receiver ON Messages(Sender, Receiver);
CREATE INDEX IF NOT EXISTS idx_participatetournament_tournament ON Participate_Tournament(T_Id);