PRAGMA foreign_keys = ON;

-- USERS TABLE
CREATE TABLE IF NOT EXISTS Users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE,
    User_name TEXT  UNIQUE,
    User_password TEXT ,
    loggedIn INTEGER  DEFAULT 0,
    Auto_Match INTEGER  DEFAULT 0,
    isOnline INTEGER  DEFAULT 0,
    avatar TEXT DEFAULT 'https://www.gravatar.com/avatar/',
    CreatedAt DATETIME  DEFAULT CURRENT_TIMESTAMP
    -- UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- FRIEND REQUEST TABLE
CREATE TABLE IF NOT EXISTS FriendRequest (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    senderId TEXT NOT NULL,
    receiverId TEXT NOT NULL,
    Request_status TEXT NOT NULL DEFAULT 'PENDING' CHECK(Request_status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (senderId, receiverId),
    FOREIGN KEY (senderId) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (receiverId) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- TOURNAMENT TABLE
CREATE TABLE IF NOT EXISTS Tournament (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Label TEXT NOT NULL DEFAULT 'New Tournament',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    result TEXT NOT NULL DEFAULT 'PENDING' CHECK(result IN ('PENDING','PLAYING','FINISHED')),
    Winner_Id TEXT DEFAULT NULL,
    max_players INTEGER DEFAULT 4,
    count_players INTEGER DEFAULT 0,
    FOREIGN KEY (Winner_Id) REFERENCES Users(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- PARTICIPATE TOURNAMENT TABLE
CREATE TABLE IF NOT EXISTS Participate_Tournament (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    P_Id TEXT NOT NULL,
    T_Id INTEGER NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (P_Id, T_Id),
    FOREIGN KEY (P_Id) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (T_Id) REFERENCES Tournament(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- MATCH TABLE
CREATE TABLE IF NOT EXISTS Match (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    P1_Id TEXT  DEFAULT NULL,
    P2_Id TEXT  DEFAULT NULL,
    P3_Id TEXT  DEFAULT NULL,
    P4_Id TEXT  DEFAULT NULL,
    score1 INTEGER NOT NULL DEFAULT 0,
    score2 INTEGER NOT NULL DEFAULT 0,
    mode INTEGER NOT NULL DEFAULT 2,
    count_players INTEGER DEFAULT 1,
    round INTEGER NOT NULL DEFAULT 1,
    P1_Ready INTEGER NOT NULL DEFAULT 0,
    P2_Ready INTEGER NOT NULL DEFAULT 0,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gameStatus TEXT DEFAULT 'PENDING' CHECK(gameStatus IN ('PENDING','PLAYING','FINISHED')),
    -- result TEXT  DEFAULT 'PENDING',  
    Winner_Id INTEGER DEFAULT NULL,
    T_Id INTEGER DEFAULT NULL,-- add here id
    FOREIGN KEY (P1_Id) REFERENCES Users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (P2_Id) REFERENCES Users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (P3_Id) REFERENCES Users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (P4_Id) REFERENCES Users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (Winner_Id) REFERENCES Users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (T_Id) REFERENCES Tournament(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- MESSAGES TABLE
CREATE TABLE IF NOT EXISTS Messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Message_Text TEXT NOT NULL,
    Sender TEXT NOT NULL,
    Receiver TEXT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Sender) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Receiver) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- -- INDEXES
-- CREATE INDEX IF NOT EXISTS idx_friendrequest_sender ON FriendRequest(senderId);
-- CREATE INDEX IF NOT EXISTS idx_friendrequest_receiver ON FriendRequest(receiverId);
-- CREATE INDEX IF NOT EXISTS idx_messages_sender_receiver ON Messages(Sender, Receiver);
-- CREATE INDEX IF NOT EXISTS idx_participatetournament_tournament ON Participate_Tournament(T_Id);



-- and count_players < max_players
CREATE TRIGGER IF NOT EXISTS  tr_T_Insert
AFTER INSERT ON Participate_Tournament
FOR EACH ROW
BEGIN
    UPDATE Tournament
    SET count_players = count_players + 1
    WHERE id = NEW.T_Id ;
END;

CREATE TRIGGER IF NOT EXISTS  tr_T_Delete
AFTER DELETE ON Participate_Tournament
FOR EACH ROW
BEGIN
    UPDATE Tournament
    SET count_players = count_players - 1
    WHERE id = OLD.T_Id;
END;


CREATE TRIGGER IF NOT EXISTS tr_Match_Update
AFTER UPDATE ON Match
FOR EACH ROW
BEGIN
    UPDATE Tournament
    SET result = 'FINISHED', Winner_Id = NEW.Winner_Id
    WHERE NEW.T_Id IS NOT NULL AND  id = NEW.T_Id   AND (SELECT COUNT(*) FROM Match WHERE T_Id = NEW.T_Id AND gameStatus = 'FINISHED') = (max_players - 1);
END;

-- Helpful indexes for tournament queries
-- CREATE INDEX IF NOT EXISTS idx_match_tournament ON Match(T_Id);
-- Note: the (T_Id, round) index is created programmatically after ensuring
-- the 'round' column exists, to avoid startup errors on legacy databases.

