PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE,
    User_name TEXT  UNIQUE,
    User_password TEXT ,
    loggedIn INTEGER  DEFAULT 0,
    Auto_Match INTEGER  DEFAULT 0,
    isOnline INTEGER  DEFAULT 0,
    avatar TEXT DEFAULT 'https://www.gravatar.com/avatar/',
    CreatedAt DATETIME  DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Tournament (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Label TEXT NOT NULL DEFAULT 'New Tournament',
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    count_players INTEGER DEFAULT 0,
    result TEXT NOT NULL DEFAULT 'PENDING' CHECK(result IN ('PENDING','PLAYING','FINISHED')),
    Winner_Id TEXT DEFAULT NULL,
    max_players INTEGER DEFAULT 8,
    FOREIGN KEY (Winner_Id) REFERENCES Users(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Participate_Tournament (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    P_Id TEXT NOT NULL,
    T_Id INTEGER NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (P_Id, T_Id),
    FOREIGN KEY (P_Id) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (T_Id) REFERENCES Tournament(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Match (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    P1_Id TEXT  DEFAULT NULL,
    P2_Id TEXT  DEFAULT NULL,
    P3_Id TEXT  DEFAULT NULL,
    P4_Id TEXT  DEFAULT NULL,
    score1 INTEGER NOT NULL DEFAULT 0,
    score2 INTEGER NOT NULL DEFAULT 0,
    mode INTEGER NOT NULL DEFAULT 2,
    count_players INTEGER DEFAULT 1,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gameStatus TEXT DEFAULT 'PENDING' CHECK(gameStatus IN ('PENDING','PLAYING','FINISHED')),
    Winner_Id INTEGER DEFAULT NULL,
    T_Id INTEGER DEFAULT NULL,
    FOREIGN KEY (P1_Id) REFERENCES Users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (P2_Id) REFERENCES Users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (P3_Id) REFERENCES Users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (P4_Id) REFERENCES Users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (Winner_Id) REFERENCES Users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (T_Id) REFERENCES Tournament(id) ON DELETE SET NULL ON UPDATE CASCADE
);

