CREATE TABLE IF NOT EXISTS Match (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    P1_Id TEXT  DEFAULT NULL,
    P2_Id TEXT  DEFAULT NULL,
    P3_Id TEXT  DEFAULT NULL,
    P4_Id TEXT  DEFAULT NULL,
    score1 INTEGER NOT NULL DEFAULT 0,
    score2 INTEGER NOT NULL DEFAULT 0,
    mode INTEGER NOT NULL DEFAULT 2,
    count_players INTEGER DEFAULT 1,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gameStatus TEXT DEFAULT 'PENDING' CHECK(gameStatus IN ('PENDING','PLAYING','FINISHED')),
    Winner_Id TEXT DEFAULT NULL,
    T_Id TEXT DEFAULT NULL
);


CREATE INDEX idx_match_p1 ON Match(P1_Id);
CREATE INDEX idx_match_p2 ON Match(P2_Id);
CREATE INDEX idx_match_p3 ON Match(P3_Id);
CREATE INDEX idx_match_p4 ON Match(P4_Id);
CREATE INDEX idx_match_status ON Match(gameStatus);
CREATE INDEX idx_match_tid ON Match(T_Id);